server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezonr=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialectMySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
api:
  prefix: api/v1